# Generated by Django 6.0.5 on 2026-05-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='hello.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='fragrance_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
